name: Question
description: Ask a question about donating documents
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ## Have a question?

        We're happy to help! Ask anything about donating documents, licensing, formats, or the DocSpec project.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant details or background (optional)
    validations:
      required: false
